blank_issues_enabled: false
contact_links:
  - name: Start a discussion (unconfirmed bugs, questions, docs)
    url: https://github.com/nikoksr/doppler-go/discussions/new
    about: Thanks for your interest in this project. Please start a discussion to ask a question or report an unconfirmed bug. If you want to report a confirmed bug, please use the bug report template.
